---
title: "Selected cell types across selection methods"
output: html_document
params:
  markers: "../../markers/CyTOF.yml"
  random_files_path: "../../data/CyTOF/random/"
  seurat_files_path: "../../data/CyTOF/Seurat-clustering/"
  AL_entropy_path: "../../data/CyTOF/Active-Learning/AL-batches-subset"
  AL_maxp_path: ""
  sce: "../../data/CyTOF/CyTOF-train.rds"
  modality: ""
  seed: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '../../')
suppressPackageStartupMessages({
  library(tidyverse)
  library(SingleCellExperiment)
  library(ComplexHeatmap)
  library(viridis)
  library(yaml)
})
source("../../pipeline/whatsthatcell-helpers.R")
```



```{r message = F}
save.image(paste0("debug-cell-select-", params$modality, "-", params$seed, ".Rdata")
if(params$modality == "scRNASeq" | params$modality == "snRNASeq"){
  fig_width = 12
  fig_height = 10
}else{
  fig_width = 7
  fig_height = 7
}

markers <- read_yaml(params$markers)$cell_types %>% 
  unlist() %>% unique()

random_files <- list.files(params$random_files_path, full.names = TRUE, pattern = "tsv")
random <- lapply(random_files, read_tsv) %>%  
  bind_rows() %>% 
  mutate(set = as.character(set))
head(random)

seurat_files <- list.files(params$seurat_files_path, full.names = TRUE, pattern = "tsv")
Seurat <- lapply(seurat_files, read_tsv) %>%  
  bind_rows() %>% 
  dplyr::rename("set" = "params") %>% 
  mutate(set = as.character(set))
head(Seurat)

AL_entropy_files <- list.files(params$AL_entropy_path, full.names = TRUE)
AL_entropy <- lapply(AL_entropy_files, read_tsv) %>% 
  bind_rows()

AL_maxp_files <- list.files(params$AL_maxp_path, full.names = TRUE)
AL_maxp <- lapply(AL_maxp_files, read_tsv) %>%
  bind_rows()

AL <- bind_rows(AL_entropy, AL_maxp)
```

```{r}
sce <- readRDS(params$sce)
dataset <- tibble(cell_id = colnames(sce),
                  gt_cell_type = sce$CellType)

if(any(grepl("CD16_32", rownames(sce)))){
  rownames(sce)[grep("CD16_32", rownames(sce))] <- "CD16-32"
}
```


```{r fig.width = 10, fig.height = 7}
random_count <- random %>% 
  group_by(set, params, cell_type) %>% 
  tally() %>% 
  mutate(selection = "random")

random_count %>% 
  separate(params, into = c("num", "cell_num", 'cor', 'corruption'), sep = '-') %>% 
  ggplot(aes(x = reorder(cell_num, as.integer(cell_num)), y = n, fill = cell_type)) +
  geom_bar(stat = 'identity', position = 'fill') +
  labs(x = "Number of cells") + 
  scale_fill_manual(values = cell_type_colours(params$modality)) +
  whatsthatcell_theme() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  facet_wrap(~set)
```

```{r fig.width = 10, fig.height = 10}
Seurat_count <- Seurat %>% 
  group_by(set, cell_type) %>% 
  tally() %>% 
  mutate(selection = "seurat")

Seurat_count %>% 
  mutate(set = gsub("cell", "", set)) %>% 
  separate(set, into = c("knn", 'knn_val', 'res', 'res_val', 'num', 'num_val', 'cor', 'corruption'), sep = '-') %>% 
  select(-c(knn, res, num, cor)) %>% 
  ggplot(aes(x = reorder(num_val, as.integer(num_val)), y = n, fill = cell_type)) +
  geom_bar(stat = 'identity', position = 'fill') +
  labs(x = "Number of cells") + 
  scale_fill_manual(values = cell_type_colours(params$modality)) +
  whatsthatcell_theme() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1)) +
  facet_grid(knn_val ~ res_val)
```

```{r fig.width = 15, fig.height = 12}
AL_count <- AL %>% 
  group_by(method, cell_type, cell_num) %>% 
  tally() %>% 
  mutate(selection = "Active-Learning")

AL_count %>% 
  mutate(method = gsub("Active-Learning-groundTruth-strategy-", "", method)) %>% 
  separate(method, into = c('strategy', 'al', 'AL_alg', 'r', 'random', 'c', 'corrupted'), sep = '-') %>% 
  select(-c(al, r, c)) %>% 
  filter(AL_alg == "rf") |>
  ggplot(aes(x = reorder(cell_num, as.integer(cell_num)), y = n, fill = cell_type)) +
  geom_bar(stat = 'identity', position = 'fill') +
  scale_fill_manual(values = cell_type_colours(params$modality)) +
  labs(x = "Number of cells", title = "RF") + 
  facet_grid(strategy ~ random + corrupted) +
  whatsthatcell_theme() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

AL_count %>% 
  mutate(method = gsub("Active-Learning-groundTruth-strategy-", "", method)) %>% 
  separate(method, into = c('strategy', 'al', 'AL_alg', 'r', 'random', 'c', 'corrupted'), sep = '-') %>% 
  select(-c(al, r, c)) %>% 
  filter(AL_alg == "multinom") |>
  ggplot(aes(x = reorder(cell_num, as.integer(cell_num)), y = n, fill = cell_type)) +
  geom_bar(stat = 'identity', position = 'fill') +
  scale_fill_manual(values = cell_type_colours(params$modality)) +
  labs(x = "Number of cells", title = "LR") + 
  facet_grid(strategy ~ random + corrupted) +
  whatsthatcell_theme() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

dataset_frequencies <- dataset %>% 
  group_by(gt_cell_type) %>% 
  tally() %>% 
  mutate(selection = "full-training-dataset", set = "1")

dataset_frequencies %>% 
  ggplot(aes(x = set, y = n, fill = gt_cell_type)) +
  geom_bar(stat = 'identity', position = 'fill') +
  labs(title = "Cell type proportions in overall dataset") +
  scale_fill_manual(values = cell_type_colours(params$modality)) +
  whatsthatcell_theme()
```


# Heatmaps

## AL selection 
### First RF
```{r fig.width= fig_width, fig.height=fig_height}
save.image("debug-cell-select.Rdata")
if(any(grepl("CellType", colnames(colData(sce))))){
  cell_type_column <- "CellType"
}else{
  cell_type_column <- "cell_type"
}


expression_heatmap <- function(sce, df, selection_method, params, modality){
  sub_sce <- sce[markers, colnames(sce) %in% df$cell_id]
  createHeatmap(sub_sce, 
              cell_type_column = cell_type_column, 
              title = paste(selection_method, '\n', params), modality = modality)
  
}

AL <- AL %>% 
  mutate(method = gsub("Active-Learning-groundTruth-strategy-", "", method)) %>% 
  separate(method, into = c('strategy', 'al', 'AL_alg', 'r', 'random', 'c', 'corrupted'), sep = '-') %>% 
  select(-c(al, r, c))

RF <- filter(AL, AL_alg == "rf")

lapply(unique(RF$strategy), function(strat){
  lapply(unique(RF$random), function(rand){
    lapply(unique(RF$corrupted), function(corrupted){
      lapply(unique(RF$cell_num), function(cell_num){
        df <- filter(RF, 
                     strategy == strat,
                     random == rand,
                     corrupted == corrupted,
                     cell_num == cell_num)
        
        expression_heatmap(sce, df, 'Active-Learning',
                           paste0('Strategy-', strat, '-random-', rand, '\ncorrupted-', corrupted, '-cell_num-', cell_num), params$modality)
      })
    })
  })
})
```

### Next LR
```{r}
LR <- filter(AL, AL_alg == "multinom")

lapply(unique(LR$strategy), function(strat){
  lapply(unique(LR$random), function(rand){
    lapply(unique(LR$corrupted), function(corrupted){
      lapply(unique(LR$cell_num), function(cell_num){
        df <- filter(LR, 
                     strategy == strat,
                     random == rand,
                     corrupted == corrupted,
                     cell_num == cell_num)
        
        expression_heatmap(sce, df, 'Active-Learning',
                           paste0('Strategy-', strat, '-random-', rand, '\ncorrupted-', corrupted, '-cell_num-', cell_num), params$modality)
      })
    })
  })
})
```


## Random selection 

```{r fig.width=fig_width, fig.height=fig_height}
  random <- random %>% 
    separate(params, into = c("num", "cell_num", 'cor', 'corruption'), sep = '-')

  lapply(unique(random$set), function(set){
    lapply(unique(random$corruption), function(corrupt){
      lapply(unique(random$cell_num), function(cell_num){
          df <- filter(random, 
                      set == set,
                      corruption == corrupt,
                      cell_num == cell_num)
          
          expression_heatmap(sce, df, 'Random',
                            paste0(set, '-corrupted-', corrupt, '-cell_num-', cell_num), params$modality)
      })
    })
  })

filter(random, set == "Set1", corruption == "0", cell_num == "100") %>% 
  expression_heatmap(sce, ., "test1", 'test2', params$modality)
```


## Seurat selection

```{r fig.height=fig_height, fig.width=fig_width}
Seurat <- Seurat %>% 
  mutate(set = gsub("cell", "", set)) %>% 
  separate(set, into = c("knn", 'knn_val', 'res', 'res_val', 'num', 'num_val', 'cor', 'corruption'), sep = '-')

lapply(unique(Seurat$knn_val), function(nearest_n){
  lapply(unique(Seurat$res_val), function(knn_resolution){
    lapply(unique(Seurat$corruption), function(corrupt){
      lapply(unique(Seurat$num_val), function(num_cell){
        df <- filter(Seurat, 
                     knn_val == nearest_n,
                     res_val == knn_resolution,
                     corruption == corrupt,
                     num_val == num_cell)
        
       paste0('knn-', nearest_n, '-res-', knn_resolution, '-corrupted-', corrupt, '-cell_num-', num_cell)
       
        expression_heatmap(sce, df, 'Seurat',
                          paste0('knn-', nearest_n, '-res-', knn_resolution, '\ncorrupted-', corrupt, '-cell_num-', num_cell), params$modality)
      })
    })
  })
})
```


